export const types = {
  uiSetError: '[UI] Set Error',
  uiRemoveError: '[UI] Remove Error',
  uiStartLoading: '[UI] Start Loading',
  uiFinishLoading: '[UI] Finish Loading',
  countriesGetCountries: '[COUNTRIES] Get Countries',
  countriesGetCountryId: '[COUNTRIES] Get Country Id',
  countriesSearchCountry: '[COUNTRIES] Search Country',
  countriesGetContinent: '[COUNTRIES] Get Continent',
  countriesGetActivities: '[COUNTRIES] Get Activities',
  countriesGetCountriesOrdered: '[COUNTRIES] Get Countries Ordered',
  activityAddActivity: '[ACTIVITY] Add Activity',
  activityGetActivities: '[ACTIVITY] Get Activities',
  activityClearActivities: '[ACTIVITY] Clear Activities',
};
